version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    container_name: "catalog.api"

  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379" 
    ports:
      - "8001:80"
    container_name: basket.api

  orderdb:
    container_name: orderdb
    environment:
     SA_PASSWORD: "Passw0rd23"
     ACCEPT_EULA: "Y"
    ports:
        - 1433:1433

  basketdb:
    container_name: basketdb
    ports:
     - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    ports:
     - 5672:5672
     - 15672:15672 

